version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.11.1
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - run:
          name: AWS EC2 deploy
          command: |
ssh -i ~/.ssh/circleci.pem ubuntu@44.203.171.61 'mkdir -p /path/to/remote/directory && cat > /path/to/remote/directory/config.yml' < config.yml
            "echo Start deploy && \
            cd ~/circleci-aws && \
            git pull && \
            npm i && \
            npm run build && \
            pm2 stop build/server && \
            pm2 start build/server && \
            echo Deploy end"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
